### ISSUE TITLE
Package using java 1.7 not building

### ISSUE THREAD

**Issue by anunes9** [feedfm/react-native-feed-media-audio-player#17]
Hey, any reason for removing Java version? This is causing my app to not build on the latest version.

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
<img width="1362" alt="Screenshot 2022-01-17 at 20 31 23" src="https://user-images.githubusercontent.com/12769835/149833805-fffd2a56-61a8-46e1-bdbb-82c9db672c87.png">

**Comment by arvkmr** [comment]
@anunes9 
compileOptions of `JavaVersion.VERSION_1_8` are not longer required on newer Android gradle plugin versions. Please upgrade your Android gradle plugin version to at least 4.2.2 and and gradle version to at least 6.7.1 and you should no longer see this issue.

**Comment by anunes9** [comment]
@arvkmr Thanks it works now!
